FROM sphinxdoc/sphinx

RUN pip3 install \
  furo==2022.12.7 \
  myst-parser==1.0.0 \
  sphinx-autobuild==2021.3.14 \
  sphinx-copybutton==0.5.1 \
  sphinx-design==0.3.0 \
  sphinxext-opengraph==0.8.1

WORKDIR /app
