name: Bug report
description: Create a report to help improve this package.
title: "[BUG]"
labels:
  - bug
body:
  - type: input
    id: php-version
    attributes:
      label: PHP version
      description: What PHP version are you using?
      placeholder: 'e.g. 8.1.5'
    validations:
      required: true
  - type: input
    id: composer-version
    attributes:
      label: Composer version
      description: What Composer version are you using?
      placeholder: 'e.g. 2.3.5'
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package version
      description: What version of this package are you using?
      placeholder: 'e.g. 0.1.0'
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system are you using?
      placeholder: 'e.g. macOS 11.4'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: A clear and concise description of what the bug is.
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: If possible, describe steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
