services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CPSIT\ProjectBuilder\:
    resource: '../src/*'
    exclude:
      - '../src/Builder/Artifact/*.php'
      - '../src/Builder/Config/*'
      - '../src/Builder/Generator/Step/CleanUpStep.php'
      - '../src/Builder/Generator/Step/DumpBuildArtifactStep.php'
      - '../src/Builder/BuildInstructions.php'
      - '../src/Builder/BuildResult.php'
      - '../src/Console/*'
      - '../src/DependencyInjection/*'
      - '../src/Event/*'
      - '../src/IO/Console/TraceableConsoleIO.php'
      - '../src/Naming/NameVariantBuilder.php'
      - '../src/Resource/Local/ProcessedFile.php'
      - '../src/Template/TemplateSource.php'

  CPSIT\ProjectBuilder\Builder\ArtifactReader:
    arguments:
      $migrations: !tagged_iterator { tag: artifact.migration, default_index_method: getVersion }

  CPSIT\ProjectBuilder\Builder\Config\Config:
    alias: 'app.config'

  CPSIT\ProjectBuilder\Builder\Generator\Generator:
    public: true

  CPSIT\ProjectBuilder\Builder\Generator\Step\Interaction\InteractionFactory:
    arguments:
      $interactions: !tagged_iterator generator.interaction

  CPSIT\ProjectBuilder\Builder\Generator\Step\StepFactory:
    arguments:
      $steps: !tagged_iterator generator.step

  CPSIT\ProjectBuilder\Builder\Writer\WriterFactory:
    arguments:
      $writers: !tagged_iterator builder.writer

  CPSIT\ProjectBuilder\IO\InputReader:
    factory: ['@app.messenger', 'createInputReader']

  CPSIT\ProjectBuilder\IO\Messenger:
    alias: 'app.messenger'

  CPSIT\ProjectBuilder\Twig\Extension\ProjectBuilderExtension:
    arguments:
      $filters: !tagged_iterator twig.filter
      $functions: !tagged_iterator twig.function

  app.config:
    class: 'CPSIT\ProjectBuilder\Builder\Config\Config'
    synthetic: true

  app.messenger:
    class: 'CPSIT\ProjectBuilder\IO\Messenger'
    synthetic: true

  # External resources
  Twig\Environment:
    calls:
      - addExtension: ['@CPSIT\ProjectBuilder\Twig\Extension\ProjectBuilderExtension']
